export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const RENOVE_INGREDIENT = "RENOVE_INGREDIENT";
export const SET_INGREDIENT = "SET_INGREDIENT";

export const FETCH_FAILURE = "FETCH_FAILURE";

export const PURCHASE_INIT = "PURCHASE_INIT";
export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS";
export const FETCH_PURCHASE = "FETCH_PURCHASE";
