export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const RENOVE_INGREDIENT = "RENOVE_INGREDIENT";
export const SET_INGREDIENT = "SET_INGREDIENT";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const FETCH_FAILURE = "FETCH_FAILURE";

export const PURCHASE_INIT = "PURCHASE_INIT";
export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS";
export const FETCH_PURCHASE = "FETCH_PURCHASE";

export const FETCH_ORDERS = "FETCH_ORDERS";
export const SET_ORDERS = "SET_ORDERS";

export const LOGIN = "LOGIN";
export const LOGGED = "LOGGED";
export const LOGOUT = "LOGOUT";
